# Generated by Django 4.0.6 on 2022-07-27 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_blogpost_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogAuthor',
            new_name='Bloggers',
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['post_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['post_date']},
        ),
        migrations.RenameField(
            model_name='bloggers',
            old_name='bio_list',
            new_name='bio_info',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
