# Generated by Django 4.0.6 on 2022-07-27 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_rename_blogauthor_bloggers_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloggers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='bloggers',
            name='last_name',
        ),
        migrations.AddField(
            model_name='bloggers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateField(auto_now=True),
        ),
    ]
